# -*- coding: utf-8 -*-
"""DB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EPrAT2NbHWSRJE4pc9TpEXrdXyvA9mY
"""

import pandas as pd
import numpy as np
import yfinance as yf
#!pip install streamlit
import streamlit as st
import plotly.graph_objects as go
from datetime import datetime, timedelta
from tempfile import template
import warnings
warnings.filterwarnings('ignore')

# Quantitative Engine

def calculate_finannce_metrics(df, risk_free_rate=0.02):
  """Calculates key financial metrics using vectorized operations"""
  # lof returns
  df['Log_Returns'] = np.log(df['Close'] / df['Close'].shift(1))

  #Annualized Volatility (Std of log returns* sqrt of trading days)
  annual_vol = df['Log_Returns'].std() * np.sqrt(252)

  #Sharpe Ratio: (ecpected return - risk free rate)/volatility
  sharpe_ratio = (df['Log_Returns'].mean() - risk_free_rate) / annual_vol

  # Maximum Drawdown (track cumulative max price to find the highest peak reached so far)
  rolling_max= df['Close'].cummax()
  drawdowns = (df['Close'] - rolling_max) / rolling_max
  max_drawdown = drawdowns.min()

  return annual_vol, sharpe_ratio, max_drawdown

# UI Configuration

st.set_page_config(page_title="The Market Analysis", layout="wide", page_icon="📈")

#Sidebar for User Inputs
st.sidebar.header("Dashboard Configuration")
ticker= st.sidebar.text_input("Ticker", "AAPL").upper()
time_period= st.sidebar.selectbox("Time Period", ("1Y", "2Y", "5Y","YTD"), index=0)

# Mappinf timeframe to days for yfinance
period_map= {"1Y": 365, "2Y":730, "5Y":1825 , "YTD":0}

# Data Execution

st.title(f"Market Analysis for {ticker}")
if ticker:
  try:
    data = yf.download(ticker, period=time_period.lower())
    if data.empty:
      st.warning("No data found. Please enter a valid ticker")
    else:
      if isinstance(data.columns, pd.MultiIndex):
        data.columns= data.columns.droplevel(1)

      # Calculate financial metrics

      vol, sharpe, mdd = calculate_finannce_metrics(data)

      # latest metrics
      curr_price = float(data['Close'].iloc[-1])
      prev_price = float(data['Close'].iloc[0])
      total_ret = (curr_price - prev_price) / prev_price

      # Displat KPI cards
      c1, c2, c3, c4 = st.columns(4)
      c1.metric("Current Price", f"${curr_price:.2f}")
      c2.metric("Annual Volatility", f"{vol:.2f}%")
      c3.metric("Sharpe Ratio", f"{sharpe:.2f}")
      c4.metric("Maximum Drawdown", f"{mdd*100:.2f}%", delta_color="inverse")

      # Visulaization Layer
      # main candelstick chart
      fig= go.Figure()

      fig.add_trace(go.Candlestick(x= data.index,
                                    open=data['Open'],
                                    high=data['High'],
                                    low=data['Low'],
                                    close=data['Close'],
                                    name='Price Action'))
      # Moving Averages
      data['MA_50']= data['Close'].rolling(window=50).mean()

      fig.add_trace(go.Scatter(x=data.index, y=data['MA_50'], name= '50 Day MA', line=dict(color='orange', width=2)))
      fig.update_layout(title=f"{ticker} Price Chart", xaxis_rangeslider_visible=False,
                        height=600, yaxis_title="Price ($)", xaxis_title="Date",
                        template="plotly_dark", margin= dict(l=0, r=0, t=30, b=0)
                        )
      st.plotly_chart(fig, use_container_width=True)

      # Volume and Return Analysis
      col_a, col_b= st.columns(2)
      with col_a:
        st.subheader("Trading Volume")
        st.bar_chart(data['Volume'])
      with col_b:
        st.subheader("Daily Log Returns")
        st.line_chart(data['Log_Returns'])


  except Exception as e:
    st.error(f"Error downloading data for {ticker}: {e}")

